### ISSUE TITLE
[Bug] flex-end적용 시 scroll 생성 안됨

### ISSUE THREAD

**Issue by origin1508** [Strong-developers/frontend#31]
## 문제
Chat페이지에서 message가 늘어나면서 overflow: auto가 적용했지만, scroll이 생성되지 않고 부모 div를 넘어가는 버그가 발생합니다.

* justify-content: flex-end를 적용한 이유는 message들이 아래에 쌓이도록 하기 위함

## 해결
* 부모 div에 justify-content: flex-end 대신 flex-direction: column적용 후 자식으로 flex:1이 적용된 div를 추가하여 위 여백을 가득 채우게 만들어서 message들이 아래에 깔리도록 함
* overflow: auto가 작동하며 스크롤이 생성이 되는 것을 확인

**Comment by FoxMon** [comment]
Good
